# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Release To Production
run-name: 'Deploy ${{ github.ref }} to ${{ github.event.inputs.environment }}'

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Environment"
        default: 'production'
        type: choice
        options:
          - 'production'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
